
[tasks."update-and-commit"]
run = "nix flake update --commit-lock-file"

[tasks."switch"]
run = 'mise run "$(hostname)"'
env.ACTION = "switch"

[tasks."ask"]
run = 'mise run switch -- --ask'

[tasks."Techcyte-DGQJV434PF"]
run = 'nh darwin ${ACTION} --hostname "$MISE_TASK_NAME" .'

[tasks."potato-bunny"]
run = 'nh os ${ACTION} --hostname "$MISE_TASK_NAME" .'

[tasks."nutmeg"]
run = 'nh os ${ACTION} --hostname "$MISE_TASK_NAME" .'
